### ISSUE TITLE
对战 @群友时候报错

### ISSUE THREAD

**Issue by Neptune1990** [MAIxxxIAM/koishi-plugin-pokemon-battle#2]
对战 @群友时候报错
日志返回
![image](https://github.com/MAIxxxIAM/koishi-plugin-pokemon-battle/assets/107494041/4e8a4f0c-b9d6-41bc-87a3-d90bce14f9c6)
数据库使用的是mysql

System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 16.19.1
    Yarn: 3.5.0

Koishi:
    Core: 4.15.7
    Console: 5.19.5
    Koishi Desktop: 0.10.7

**Comment by MAIxxxIAM** [comment]
没用过mysql，0.4.13已经将这两个字段类型改成了timestamp，可以尝试一下是否兼容。🫡🫡

**Comment by Neptune1990** [comment]
停止后升级宝可梦命令可用 只是对战依然报
![image](https://github.com/MAIxxxIAM/koishi-plugin-pokemon-battle/assets/107494041/90bebd4b-0f85-47f7-ae88-13116b551dbb)

**Comment by MAIxxxIAM** [comment]
用的是什么适配器

**Comment by Neptune1990** [comment]
red

**Comment by MAIxxxIAM** [comment]
加急修复了mysql无法读写时间戳数据的问题（，可以更新至最新版本。
