### ISSUE TITLE
pokeBase 里面 spec 的计算似乎有点问题

### ISSUE THREAD

**Issue by liggest** [MAIxxxIAM/koishi-plugin-pokemon-battle#4]
https://github.com/MAIxxxIAM/koishi-plugin-pokemon-battle/blob/8b5df7d99747816a56e1807423ca5d43ac57752f/lib/module/pokemon.js#L47

冒号后面写的还是 `hp`，而不是 `spec`
之前好像有群友杂交出来的宝可梦特殊和生命是一个数，不知道和这个有无关系

**Comment by MAIxxxIAM** [comment]
oooooo,好像确实，这两天有时间修一下。

**Comment by MAIxxxIAM** [comment]
几天前已修复
